Repository likelion-backend-6th/studyon, pull requests merged in 2023-10, with the labels that each got.

#90 Update) 스터디 관리 페이지 좋아요 버튼 삭제
  templates/studies/index.html
Labels: enhancement

#92 Feat) 모집 생성(스터디 생성) 기능 추가
  recruit/urls.py
  recruit/views.py
  templates/recruits/index.html
  templates/recruits/recruit_form.html
Labels: enhancement

#98 Feat) 모집글 수정 페이지
  recruit/urls.py
  recruit/views.py
  templates/recruits/recruit_form.html
  templates/studies/index.html
Labels: enhancement

#102 Feat) 모집글 삭제 기능 추가
  recruit/urls.py
  recruit/views.py
  templates/recruits/recruit_confirm_delete.html
  templates/studies/index.html
Labels: enhancement

#104 Fix) LoginRequired 추가
  recruit/views.py
Labels: enhancement

#108 Update) LoginRequiredMixin에 로그인 페이지 리디렉션 추가
  manager/views.py
Labels: enhancement

#109 Update) LoginRequiredMixin 원상복귀 및 login_url 설정
  manager/views.py
Labels: enhancement

#111 스터디 관리 상세 페이지 디자인 적용
  static/css/base.css
  templates/studies/detail.html
Labels: enhancement

#113 진행상황 파일 이름 변경
  Weekly_Log/[1주차] Project_2팀_진행상황_공유.md
Labels: documentation

#123 모델 간단 수정
  manager/migrations/0003_alter_post_files.py
  manager/models.py
  recruit/migrations/0003_alter_recruit_creator.py
  recruit/models.py
Labels: enhancement

#135 Update) 검색 기능 키워드 추가
  recruit/views.py
Labels: enhancement

#138 Update) 날짜 필드 변경, formview 변경, 생성시 작성자도 멤버에 추가
  recruit/forms.py
  recruit/views.py
Labels: enhancement

#145 main header에 내 정보 추가
  templates/base.html
Labels: enhancement

#147 메인에서 공고 카드에 좋아요 개수 표시
  templates/recruits/index.html
Labels: enhancement

#148 Update) tags, file 저장
  recruit/views.py
  templates/recruits/recruit_form.html
Labels: enhancement

#149 Update) 파일 업로드 변경
  recruit/forms.py
  recruit/views.py
Labels: enhancement

#151 메인페이지 너비 살짝 수정
  static/css/base.css
  templates/recruits/index.html
Labels: enhancement

#153 Feat) 소셜 로그인 ( 네이버, 구글, 깃헙 ) 기능 구현
  config/settings/base.py
  config/urls.py
  templates/socialaccount/signup.html
  templates/users/login.html
Labels: enhancement

#160 Update) 무한스크롤
  recruit/views.py
  templates/base.html
  templates/recruits/index.html
Labels: enhancement

#163 Update) paginate 수정
  recruit/views.py
  templates/recruits/index.html
Labels: enhancement

#166 스타일 실수 수정
  templates/recruits/recruit_form.html
Labels: bug

#191 base.html을 docker에서 build
  .gitignore
  Dockerfile
  static/css/base.css
Labels: enhancement

#193 메인 페이지 디자인 변경
  templates/recruits/index.html
Labels: enhancement

#197 키워드 표시 문제 해결
  recruit/views.py
  templates/recruits/index.html
Labels: bug

#199 내 정보 페이지 디자인
  templates/users/info.html
Labels: enhancement

#201 Update) login 페이지 스타일 수정
  static/css/base.css
  templates/users/login.html
Labels: enhancement

#205 Update) signup 페이지 스타일
  templates/users/login.html
  templates/users/signup.html
Labels: enhancement

#211 Update) 무한 스크롤 시 url에 query 추가
  templates/recruits/index.html
Labels: enhancement

#213 actions djLint check 추가
  .github/workflows/Test.yaml
Labels: enhancement

#222 Fix) 모집 생성 시 에러 메세지 미출력
  templates/recruits/recruit_form.html
Labels: enhancement

#231 모집폼 테그 선택 버그 해결
  recruit/views.py
  templates/recruits/recruit_form.html
Labels: bug

#235 화상채팅에 coturn server 추가
  static/js/video.js
Labels: enhancement

#237 ice exchange 로직 변경
  static/js/video.js
Labels: enhancement

#240 websocket 에러 해결
  config/asgi.py
  config/routing.py
  static/js/video.js
  video/consumers.py
  video/routing.py
Labels: bug

#241 [2주차] Project_2팀 진행상황 공유
  Weekly_Log/[2주차] Project_2팀_진행상황_공유.md
  Weekly_Log/image/week2.png
Labels: documentation

#243 peer가 disconnected되는 문제 수정
  static/js/video.js
Labels: enhancement

#256 Feat) 채팅방 웹소켓 비정상 종료 시, 재연결 기능 추가
  templates/chat/room.html
Labels: enhancement

#257 Update) 스터디 상세 페이지 디자인 수정
  templates/studies/detail.html
Labels: enhancement

#258 WS router 설정 방식 수정
  chat/routing.py
  config/asgi.py
  config/routing.py
  message/routing.py
  static/js/video.js
  video/routing.py
Labels: enhancement

#259 Update) Task 수정 페이지 디자인 추가
  templates/studies/detail.html
  templates/studies/tasks/create.html
  templates/studies/tasks/modify.html
Labels: enhancement

#262 Update) 스터디 관리 상세 페이지 디자인 수정
  templates/studies/detail.html
  templates/studies/index.html
Labels: enhancement

#273 Update) 스터디 관리 페이지 유저목록 디자인 수정
  templates/studies/detail.html
Labels: enhancement

#278 prometheus 설정
  chat/models.py
  config/settings/base.py
  config/settings/prod.py
  config/settings/staging.py
  config/urls.py
  manager/models.py
  message/models.py
  recruit/models.py
  requirements.txt
  user/models.py
Labels: enhancement

#282 Update) 스터디 모집완료 로직 문제 관련 수정
  recruit/views.py
  templates/recruits/index.html
  templates/studies/index.html
Labels: enhancement

#283 Update) Task 생성 에러 수정
  manager/views.py
  templates/studies/tasks/create.html
Labels: enhancement

#284 Update) 메인 페이지 paginate, 오류 메시지 스타일, 오타 수정
  recruit/views.py
  templates/recruits/index.html
  templates/recruits/recruit_form.html
Labels: duplicate

#290 Update) 스터디관리 메인페이지 디자인 수정
  templates/studies/index.html
Labels: enhancement

#297 Fix) staging 설정 파일 - CACHES 설정 오류 변경
  config/settings/staging.py
Labels: enhancement

#301 Update) 소셜로그인 중복 페이지 디자인 추가
  templates/socialaccount/signup.html
  user/views.py
Labels: enhancement

#304 Docs) 배포 메뉴얼 이미지 추가
  static/image/deploy_manual/deploy01.png
  static/image/deploy_manual/deploy02.png
  static/image/deploy_manual/deploy03.png
  static/image/deploy_manual/deploy04.png
  static/image/deploy_manual/deploy05.png
  static/image/deploy_manual/deploy06.png
  static/image/deploy_manual/deploy07.png
Labels: documentation

#306 Update) Task 생성 시 기간을 스터디 기간 안에 설정할 수 있도록 변경
  manager/views.py
Labels: enhancement

#311 Update) 모집글 목록에 is_active가 True인 모집글만 출력
  recruit/views.py
Labels: enhancement

#313 Fix) 모집글 목록 무한 스크롤 수정
  templates/recruits/index.html
Labels: enhancement

#314 3주차 weekly log
  Weekly_Log/[3주차] Project_2팀_진행상황_공유.md
  Weekly_Log/image/week3.png
Labels: documentation

#315 Update) 스터디 입장,퇴장 알림 수정
  message/consumers.py
  templates/chat/room.html
  templates/studies/detail.html
Labels: enhancement

#317 Fix) 메인 페이지 무한 스크롤 수정2, queryset 수정
  recruit/views.py
  templates/recruits/index.html
Labels: enhancement

#319 회원가입 시 비밀번호 리턴값이 없던 오류, 비밀번호 검증기능 추가
  user/forms.py
Labels: enhancement

#324 스터디 상세 디자인/기능 수정
  static/js/review.js
  templates/studies/detail.html
Labels: enhancement

#334 스터디 상세 버튼 출력 에러 수정
  templates/studies/detail.html
Labels: bug

#336 Update) Task 수정 페이지 수정 버튼 변경
  templates/studies/tasks/modify.html
Labels: enhancement

#337 모집글 수정시 tag가 자동 선택되도록 수정
  static/js/tagList.js
  templates/recruits/recruit_form.html
Labels: bug

#340 tag 필수선택 에러 표시되도록 수정
  templates/recruits/recruit_form.html
Labels: bug

#349 Fix) 오타 수정 User -> Notice
  message/permissions.py
Labels: bug

#354 리뷰에 스터디 정보 추가
  user/migrations/0004_review_study_review_user_review_study_i_86d74d_idx.py
  user/models.py
  user/tests.py
  user/views.py
Labels: enhancement

#360 Fix) 스터디당 채팅방 개수를 3개 이하로 제한
  chat/management/commands/06_room.py
Labels: bug

#365 Fix) 모집글 생성 시, 중복 모집신청 데이터 생성
  recruit/management/commands/02_rs.py
Labels: bug

#375 Update) 내 정보 페이지 디자인 수정
  templates/users/info.html
Labels: enhancement

#379 Fix) 메인 페이지 카드 세로 길이 에러 해결
  templates/recruits/index.html
Labels: bug

#381 Fix) 모집글 정렬을 마감일 기준 정순으로 정렬
  recruit/views.py
Labels: bug

#384 FIx) 모집글 더미데이터가 오늘보다 뒤의 일자로 생성되도록 수정
  recruit/management/commands/02_rs.py
Labels: bug

#385 Update) 모집글 상세, 내정보 페이지 좌우 여백 추가
  templates/recruits/detail.html
  templates/users/info.html
Labels: enhancement

#387 Fix) 알림메세지가 3초간 떠있도록 수정
  templates/base.html
  templates/popup.html
Labels: enhancement

#389 Update) 마감일이 지난 모집글 안뜨게 변경, 마감일이 오늘 이전 날짜에 설정 못하게 변경
  recruit/views.py
Labels: bug

#392 Fix) 검색 쿼리 존재 시, x 버튼 추가
  templates/recruits/index.html
Labels: enhancement

#393 Update) url 에서 끝에 / 빠진것 추가
  chat/urls.py
  manager/urls.py
Labels: enhancement

#394 Update) 주석처리 해제
  templates/studies/index.html
Labels: enhancement

#396 Update) 임정택 - ERD 변경
  README.md
  static/image/README/StudyOn.png
  static/image/README/erd.png
Labels: enhancement

#398 Fix) 확인창에서 아니오 선택 시 폼 제출되는 에러 해결
  templates/studies/index.html
Labels: bug
